### ISSUE TITLE
JS Generators

### ISSUE THREAD

**Issue by rudijs** [dylanb/gulp-coverage#21]
Hi,

Currently code coverage for es6 generators won't work due to esprimajs not supporting them right?

Example err:

    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: Line 9: Unexpected token *
        at throwError (/projects/node_modules/gulp-coverage/contrib/esprima.js:1470:21)
        at throwUnexpected (/projects/node_modules/gulp-coverage/contrib/esprima.js:1527:9)

I'm tinkering with KoaJS and was trying to test some routes which use generator functions.

Gulp task is:

```
  gulp.task('test', function () {
    return gulp.src(['app/**/*.spec.js'], { read: false })
      .pipe(cover.instrument({
        pattern: [
          'app/**/*.js',
          '!app/**/*.spec.js'
        ],
        debugDirectory: 'test/debug'
      }))
      .pipe(mocha())
      .pipe(cover.report({
        outFile: 'test/coverage.html'
      }));
```

Using mocha manually on the command line (no coverage) the tests run OK with the --harmony flag.

Have tinkered with this (no joy):

    .pipe(mocha({harmony: true}))

Thanks.

**Comment by dylanb** [comment]
Closing this issue because it is in fact a shortcoming in esprima
