### ISSUE TITLE
0% line coverage, 0% statement coverage, 0% block coverage, 0 SLOC...?

### ISSUE THREAD

**Issue by jamesmorgan** [dylanb/gulp-coverage#32]
I have been unable to successfully generate code coverage for my nodejs test code and wondered if there may be in issue with either the version of gulp-jasmine or some other dependency I am using?

The gulp task I am running looks like this:

``` javascript
gulp.task('server-unit-tests', function () {
    return gulp.src('./server/**/*.js', { read: false })
        .pipe(cover.instrument({
            pattern: ['./server/test/**/*.spec.js']
        }))
        .pipe(jasmine({
            verbose: true,
            includeStackTrace: true
        }))
        .pipe(cover.gather())
        .pipe(cover.format([
            { reporter: 'html', outFile: 'coverage.html' },
            { reporter: 'json', outFile: 'coverage.json' }
        ]))
        .pipe(gulp.dest('./server/coverage'));
});
```

This generates the following `.json` file:

``` json
{
 "files": [],
 "sloc": 0,
 "ssoc": 0,
 "sboc": 0,
 "coverage": null,
 "statements": null,
 "blocks": null,
 "uncovered": [
  "server/test/config.spec.js",
  "server/test/utils/cypher-promise.spec.js"
 ]
}
```

The `html` output looks like:
![screenshot 2014-10-06 22 13 26](https://cloud.githubusercontent.com/assets/110869/4533614/b2da9372-4d9d-11e4-9d9f-ddb7a754241a.png)

I originally thought it maybe due to a different version of one of the libraries but when I checked out the latest code from here and when I run `gulp` on `gulp-coverage` I always see one of the jasmine test showing as 0% coverage and wondered if this could be related?

![screenshot 2014-10-06 22 15 57](https://cloud.githubusercontent.com/assets/110869/4533664/09268196-4d9e-11e4-957e-1242fe06bf77.png)

My package versions:

```
{
    "gulp": "^3.8.8",
    "gulp-coverage": "^0.3.31",
    "gulp-jasmine": "^1.0.0"
}
```

Have I missed something obvious?

**Comment by miparnisari** [comment]
I have the same problem with this code: https://github.com/miparnisari/node-cognitive-services/tree/fixes

Any ideas? Here is my gulpfile:

```javascript
var gulp = require('gulp');
var mocha = require('gulp-mocha');
var cover = require('gulp-coverage');

gulp.task('test', () => {
    return gulp.src('test/*.js')
        .pipe(cover.instrument({
            pattern: ['index.js', 'api/*.js', 'lib/*.js'],
            debugDirectory: 'debug'
        }))
        .pipe(mocha({
            timeout: 15000
        }))
        .pipe(cover.gather())
        .pipe(cover.format([
            { reporter: 'html', outFile: 'coverage.html' },
            { reporter: 'json', outFile: 'coverage.json' }
        ]))
        .pipe(gulp.dest('reports'));
});
```
