### ISSUE TITLE
Should gather() add a vinyl object to the stream ?

### ISSUE THREAD

**Issue by iandotkelly** [dylanb/gulp-coverage#38]
I was thinking of using this on a project, but I want to pipe the lcov file to coveralls, not just consume it in format() - but the object put into the stream by gather() isn't a vinyl file object.  This breaks all the downstream plugins I've tried to use with it.

Any objection to me submitting a PR for this - making the thing passed between the separate plugins a vinyl object?

Any problem you would see with doing this?  You've modified the lcov format, do you think it would still work with other reporting tools like coveralls?

**Comment by dylanb** [comment]
Is this what you mean

https://github.com/dylanb/gulp-coverage/blob/master/gulpfile.js#L71

**Comment by iandotkelly** [comment]
Oh cool - so the reporter has an lcov output, I wasn't aware that you had an lcov formatter and assumed I had to use the json added to the stream by gather().

That fixes my problem thanks!

If you treat gather as an isolated plugin through, it breaks gulp conventions by not adding a vinyl file object to the stream - but if format() does then this is not such a big deal since no-one is going to consume the output of gather directly.
